### ISSUE TITLE
Seeking Advice on Handling Model Changes and Embedding Dimensions

### ISSUE THREAD

**Issue by alnutile** [pgvector/pgvector-php#11]
I've recently transitioned from using the "text-similarity-babbage-001" model to "text-embedding-ada-002" and encountered the following error:

```
PDOException: SQLSTATE[22000]: Data exception: 7 ERROR: expected 2048 dimensions, not 1536 in /home/forge/larachain.io/releases/20240326200550/vendor/laravel/framework/src/Illuminate/Database/Connection.php:603
```

Considering I have done 2 other updates before this 

First: 
```php
        Schema::create('documents', function (Blueprint $table) {
            $table->id();
            ////stuff here
            $table->vector('embedding', 1536)->nullable()l
        });
```

then:

```php
        Schema::table('messages', function (Blueprint $table) {
            $table->integer('token_count')->nullable();
            $table->vector('embedding', 2048)->nullable();
        });
```

It seems I am now going back 🤪

Is there a better way I should be using this library to be more flexible with LLM model changes?
 
Thanks!

**Comment by ankane** [comment]
Hi @alnutile, the two main ways to handle multiple embedding models are:

1. Add a new column for each model - `embedding vector(2048)`, `ada_embedding vector(1536)`, etc.
2. Create a separate `message_embeddings` (or `embeddings`) table with `message_id` (or a polymorphic relationship), `model`, and `embedding vector` ([example](https://github.com/pgvector/pgvector?tab=readme-ov-file#can-i-store-vectors-with-different-dimensions-in-the-same-column))

**Comment by alnutile** [comment]
Makes sense thanks!
