### ISSUE TITLE
Laravel & Type Casts

### ISSUE THREAD

**Issue by CLCWebsiteServices** [pgvector/pgvector-php#14]
So I've got the following test code:
```php
$vectorArray = FaceEmbedding::first()->embedding; //returns a Vector::class cast from my model which is a VECTOR(2056)
$documents = FaceEmbedding::orderByRaw('embedding <-> ?', [$vectorArray])->take(5)->get()
```
However, upon running the code I get the following error:
```
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: public.vector <-> unknown LINE 1: ...elect * from "face_embeddings" order by embedding <-> $1 lim... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. (Connection: pgsql, SQL: select * from "face_embeddings" order by embedding <-> [0,128,250,68,0,0,156,66,255,56,29.......
```
But when I do the following:
```php
$documents = FaceEmbedding::orderByRaw('embedding <-> ?', [$vectorArray])->take(5)->toRawSql()
```
And copy it directly into my postgres console, it works perfectly fine?

**Comment by ankane** [comment]
Hi @CLCWebsiteServices, I'm not able to reproduce the issue and recommend using `nearestNeighbors`, but you could try using `embedding <-> ?::vector` to see if that fixes it.

**Comment by CLCWebsiteServices** [comment]
Okay, so I've found out the issue... when I'm doing it via eloquent I've printed out the `toRawSql()` it's doing the following:
```sql
select * from "face_embeddings" order by embedding <-> '[0,128,250,68,0,0,156,66,255,56,2
```
But infact I need it to do the following:
```
select * from vector.face_embeddings order by embedding <-> '[0
```

**Comment by CLCWebsiteServices** [comment]
Yeah, appears that when doing schema it isn't working correctly as it's trying to get the `vector` datatype from the public schema rather than my created `vector` schema that I placed the `face_embeddings` inside.
