### ISSUE TITLE
Laravel support

### ISSUE THREAD

**Issue by C0chett0** [pgvector/pgvector-php#3]
It should be noted that in this state the package only supports Laravel starting with version 10.

The two methods get and set from Illuminate\Contracts\Database\Eloquent\CastsAttributes has been modified in this version. The type hinting Model for the first parameter has been added at that point. By the way the mixed type on third parameter has also been added then but being mixed it doesn't raise any error.

Older Laravel versions do not have those two type hinting [(9.x),](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Contracts/Database/Eloquent/CastsAttributes.php) which prompts an error with latests PHP versions (maybe 7.4 isn't as strict as 8.x ...)

Maybe we could have a tag without those type hint for older Laravel versions ?

**Comment by ankane** [comment]
Hi @C0chett0, thanks for reporting. Pushed a fix in the commit above.

**Comment by C0chett0** [comment]
Thanks a lot !
